# Generated by Django 3.1.3 on 2020-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
